---
metaStoreOptions:
  providerClassName: "com.flipkart.varadhi.db.ZookeeperProvider"
  configFile: "src/main/resources/zkConfig.yml"

roleDefinitions:
  project.admin:
    roleId: project.admin
    permissions:
      - PROJECT_CREATE
      - PROJECT_UPDATE
  team.admin:
    roleId: team.admin
    permissions:
      - TEAM_CREATE
      - TEAM_UPDATE
