varadhiOptions:
  deployedRegion: "default"
  producerOptions:
    producerCacheBuilderSpec: ""
    topicCacheBuilderSpec: ""

vertxOptions:
  eventLoopPoolSize: 1
  workerPoolSize: 1
  internalBlockingPoolSize: 1

verticleDeploymentOptions:
  instances: 1
  worker: false
  workerPoolSize: 2

authenticationEnabled: false

authentication:
  jwt:
    jwksUrl: "http://localhost:9090/default/jwks"
    options:
      issuer: "http://localhost:9090/default"
      ignoreExpiration: true

authorizationEnabled: true

authorization:
  superUsers: [ "thanos" ]
  providerClassName: "com.flipkart.varadhi.auth.DefaultAuthorizationProvider"
  providerOptions: >
    {
      "roles": {
        "org.admin": [
          "ORG_CREATE",
          "ORG_UPDATE",
          "ORG_GET",
          "ORG_DELETE"
        ],
        "team.admin": [
          "TEAM_CREATE",
          "TEAM_GET",
          "TEAM_UPDATE"
        ]
      },
      "roleBindings": {
        "flipkart": {
          "aayush.gupta": [
            "org.admin",
            "team.admin"
          ],
          "abc": [
            "team.admin"
          ],
          "xyz": [
            "org.admin"
          ]
        }
      }
    }

messagingStackOptions:
  providerClassName: "com.flipkart.varadhi.pulsar.PulsarStackProvider"
  configFile: "src/main/resources/pulsarConfig.yml"

metaStoreOptions:
  providerClassName: "com.flipkart.varadhi.db.ZookeeperProvider"
  configFile: "src/main/resources/zkConfig.yml"

httpServerOptions:
  port: 8080
  alpnVersions: [ "HTTP_1_1", "HTTP_2" ]
  decompressionSupported: false
  useAlpn: true
