#####################################################################
# ConfigMap for Varadhi messaging stack dependency.
# Actual config keys/values are defined in stack specific .tpl file
#####################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "varadhi.name" . }}-{{ .Values.deployment.name }}-{{ .Values.messaging.configMapName }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "varadhi.commonLabels" . | nindent 4 }}
    component: {{ .Values.deployment.name }}
data:
  messaging.yml: |
    {{- if .Values.messaging.pulsar }}
    {{ include "configMap.messaging.pulsar" .  | nindent 4}}
    {{- end }}
