#####################################################################
# ConfigMap for Varadhi metastore dependency.
# Actual config keys/values are defined in stack specific .tpl file
#####################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "varadhi.name" . }}-{{ .Values.deployment.name }}-{{ .Values.metastore.configMapName }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "varadhi.commonLabels" . | nindent 4 }}
    component: {{ .Values.deployment.name }}
data:
  metastore.yml: |
    {{- if .Values.metastore.zookeeper }}
    {{ include "configMap.metastore.zookeeper" . | nindent 4}}
    {{- end }}
