# To run the e2e tests.
# currently setup on dev branch.
name: E2E 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: dhruv-dev
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: 'gradle'
    - name: Setup Gradle 5.6.4
      uses: gradle/gradle-build-action@v2.4.2
      with:
        gradle-version: 5.6.4
    - name: Execute Gradle build 
      run: ./gradlew clean build copyDependencies
    - name: Build the Docker image
      run: docker build . --file setup/docker/Dockerfile --tag varadhi.docker.registry/varadhi:latest --build-arg ENV=test
    - name: Clean the environment
      run: docker volume rm $(docker volume ls -q | egrep -E 'zk|pulsar')
    - name: Setup the environment
      run: docker compose --profile test -f setup/docker/compose.yml up
    - name: wait
      run: sleep 120
    - name: Run the test
      run: ./gradlew test testE2E
    - name: Tear down the docker containers
      run: docker compose --profile test -f setup/docker/compose.yml down
    - name: Tear down the data volumes
      run: docker volume rm $(docker volume ls -q | egrep -E 'zk|pulsar')
